### ISSUE TITLE
Server panics on creating a new entry with the same deleted key

### ISSUE THREAD

**Issue by HotPotatoC** [HotPotatoC/kvstore#8]
A Runtime error occurred when trying to set an entry with the same key as the former

**CLI**
```
127.0.0.1:7275> set key value
OK
127.0.0.1:7275> list
1 items
key -> "value"

127.0.0.1:7275> del key
1
127.0.0.1:7275> set key value
```

**SERVER**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x68e891]

goroutine 8 [running]:
github.com/HotPotatoC/kvstore/pkg/hashtable.(*HashTable).insert(0xc00002aa00, 0xc000016ce0, 0x3, 0xc000016ce4, 0x5, 0x0)
        /home/juanchristian/go/src/github.com/HotPotatoC/kvstore/pkg/hashtable/hash_table.go:183 +0x1b1
github.com/HotPotatoC/kvstore/pkg/hashtable.(*HashTable).Set(0xc00002aa00, 0xc000016ce0, 0x3, 0xc000016ce4, 0x5)
        /home/juanchristian/go/src/github.com/HotPotatoC/kvstore/pkg/hashtable/hash_table.go:61 +0xb0
github.com/HotPotatoC/kvstore/database.(*database).Set(0xc0000100b0, 0xc000016ce0, 0x3, 0xc000016ce4, 0x5)
        /home/juanchristian/go/src/github.com/HotPotatoC/kvstore/database/database.go:46 +0x56
github.com/HotPotatoC/kvstore/command.setCommand.Execute(0x7e71d0, 0xc0000100b0, 0xc000062660, 0x2, 0x2, 0x1, 0x2, 0xc000062660)
        /home/juanchristian/go/src/github.com/HotPotatoC/kvstore/command/set_command.go:35 +0x118
github.com/HotPotatoC/kvstore/server.(*Server).onMessage(0xc00007d590, 0x7e7280, 0xc0000100c8, 0xc000200000, 0x9000, 0x9000)
        /home/juanchristian/go/src/github.com/HotPotatoC/kvstore/server/hooks.go:49 +0x3ac
github.com/HotPotatoC/kvstore/pkg/tcp.(*Server).handleConnection(0xc00007d620, 0x7e7280, 0xc0000100c8)
        /home/juanchristian/go/src/github.com/HotPotatoC/kvstore/pkg/tcp/tcp.go:90 +0x2c2
github.com/HotPotatoC/kvstore/pkg/tcp.(*Server).acceptConnections.func1(0xc00007d620, 0x7e7280, 0xc0000100c8)
        /home/juanchristian/go/src/github.com/HotPotatoC/kvstore/pkg/tcp/tcp.go:62 +0x65
created by github.com/HotPotatoC/kvstore/pkg/tcp.(*Server).acceptConnections
        /home/juanchristian/go/src/github.com/HotPotatoC/kvstore/pkg/tcp/tcp.go:60 +0x7a
```

**Comment by HotPotatoC** [comment]
fixed 9dd0b61
